const socket=io();
const tg=window.Telegram?.WebApp; tg?.ready(); tg?.expand();
const $=s=>document.querySelector(s); const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let me=null, replyTo=null, media=null, voiceRoom='lobby';
const texts={uz:['Til','Yoshingiz','Jinsingiz','Davom etish','Asosiy chat','Kontaktlar','Ovozli xona','Xabar yozing...'],en:['Language','Your age','Gender','Continue','Main chat','Contacts','Voice room','Write a message...'],ru:['Язык','Ваш возраст','Пол','Продолжить','Главный чат','Контакты','Голосовая комната','Введите сообщение...'],tr:['Dil','Yaşınız','Cinsiyet','Devam','Ana sohbet','Kişiler','Sesli oda','Mesaj yazın...']};
function applyLang(){const a=texts[$('#language').value]||texts.en; document.querySelectorAll('[data-t]').forEach((e,i)=>e.textContent=a[i]||e.textContent); $('#messageInput').placeholder=a[7];}
$('#language').onchange=applyLang; applyLang();
$('#profileForm').onsubmit=e=>{e.preventDefault(); const age=+$('#age').value;if(age<13||age>120)return alert('Yoshni to‘g‘ri kiriting.'); const tu=tg?.initDataUnsafe?.user||{}; socket.emit('register',{initData:tg?.initData||'',telegramUser:tu,name:$('#name').value.trim(),age,gender:$('#gender').value,language:$('#language').value},r=>{if(!r.ok)return alert(r.error||'Xatolik');me=r.user;$('#onboarding').classList.add('hidden');$('#app').classList.remove('hidden');loadHistory();});};
function loadHistory(){socket.emit('get-history',null,arr=>arr.forEach(renderMessage));}
function renderMessage(m){if(m.deleted||document.querySelector(`[data-mid="${m.id}"]`))return;const mine=m.from===me?.id;const el=document.createElement('article');el.className='msg '+(mine?'mine':'');el.dataset.mid=m.id;el.innerHTML=`<div class="bubble"><b>${mine?'Siz':esc(m.from)}</b><div class="reply">${m.replyTo?'↪ javob': ''}</div><div>${esc(m.text)}</div><small>${new Date(m.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small>${mine?'<button class="del">🗑</button>':''}</div>`;el.onclick=ev=>{if(ev.target.classList.contains('del'))socket.emit('delete-message',{id:m.id});else if(!ev.target.closest('button')){replyTo=m.id;$('#replyBar').textContent='↪ Xabarga javob berish · bekor qilish';$('#replyBar').classList.remove('hidden');}};$('#messages').append(el);el.scrollIntoView({block:'end'});}
socket.on('message',renderMessage);socket.on('message-deleted',({id})=>document.querySelector(`[data-mid="${id}"]`)?.remove());
$('#composer').onsubmit=e=>{e.preventDefault();const text=$('#messageInput').value.trim();if(!text)return;socket.emit('send-message',{text,replyTo},()=>{});$('#messageInput').value='';replyTo=null;$('#replyBar').classList.add('hidden');};
$('#replyBar').onclick=()=>{replyTo=null;$('#replyBar').classList.add('hidden');};
$('.nav').onclick=e=>{const b=e.target.closest('button');if(!b)return;document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.panel').forEach(x=>x.classList.add('hidden'));$('#'+b.dataset.panel).classList.remove('hidden');};
$('#joinVoice').onclick=async()=>{try{media=await navigator.mediaDevices.getUserMedia({audio:true});$('#voiceState').textContent='Mikrofon ulandi. Bu minimal WebRTC signaling asosidir.';socket.emit('join-room',{roomId:voiceRoom});$('#leaveVoice').classList.remove('hidden');}catch{alert('Mikrofon ruxsati kerak');}};
$('#leaveVoice').onclick=()=>{media?.getTracks().forEach(t=>t.stop());media=null;$('#voiceState').textContent='Xonaga kirmagansiz';$('#leaveVoice').classList.add('hidden');};
socket.on('presence',({user,online})=>{if(user.id===me?.id)return;let el=document.querySelector(`[data-uid="${user.id}"]`);if(!el){el=document.createElement('div');el.dataset.uid=user.id;$('#contactsList').append(el);}el.textContent=`${user.name} ${online?'● online':'○ offline'}`;});
